### ISSUE TITLE
Google Chrome Not found

### ISSUE THREAD

**Issue by mikedvzo** [aiyodk/Alfred-Extensions#13]

**Comment by aiyodk** [comment]
Hi,

Google Chrome has the CFB bundle identifier “com.google.Chrome" so try this command instead:
mdfind "kMDItemCFBundleIdentifier == 'com.apple.Chrome’"

The cache that SendURL uses might be corrupted. It regenerate its cache each time it opens an app, so try to use one of the other options SendURL offers (e.g. "Copy URL”). Then call SendURL again and see if Chrome is there. If not please let me know.  

Cheers
Jonas

**Comment by mikedvzo** [comment]
Thx thought I deleted that message or at least I tried to - that was a typo.  The reason it stopped working is because my MDS DB was corrupted and Google Chrome was not in Spotlight and could not be updated.  I had to reindex.  

-- 
Michael DiVincenzo
divincem@gmail.com 
919.392.2265 (Main)
919.741.8314 (Mobile)

On December 08, 2015 at 2:37:41 PM, Jonas Eriksen (notifications@github.com) wrote:

Hi,

Google Chrome has the CFB bundle identifier “com.google.Chrome" so try this command instead:
mdfind "kMDItemCFBundleIdentifier == 'com.apple.Chrome’"

The cache that SendURL uses might be corrupted. It regenerate its cache each time it opens an app, so try to use one of the other options SendURL offers (e.g. "Copy URL”). Then call SendURL again and see if Chrome is there. If not please let me know.

Cheers
Jonas

**Comment by aiyodk** [comment]
Hi,

Great to hear everything is working again!

Cheers
Jonas 

On 08 Dec 2015, at 20:46, mikedvzo notifications@github.com wrote:

Thx thought I deleted that message or at least I tried to - that was a typo.  The reason it stopped working is because my MDS DB was corrupted and Google Chrome was not in Spotlight and could not be updated.  I had to reindex.  

## 

Michael DiVincenzo
divincem@gmail.com 
919.392.2265 (Main)
919.741.8314 (Mobile)

On December 08, 2015 at 2:37:41 PM, Jonas Eriksen (notifications@github.com) wrote:

Hi,

Google Chrome has the CFB bundle identifier “com.google.Chrome" so try this command instead:
mdfind "kMDItemCFBundleIdentifier == 'com.apple.Chrome’"

The cache that SendURL uses might be corrupted. It regenerate its cache each time it opens an app, so try to use one of the other options SendURL offers (e.g. "Copy URL”). Then call SendURL again and see if Chrome is there. If not please let me know.

Cheers
Jonas
